services:
  - type: web
    name: users-management-spring-boot-hexagonal-ddd
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_ADDRESS
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: SECURITY_JWT_SECRET
        sync: false